# replacing Labels(strings)with numbers & vice versa

In [ ]:
#https://www.geeksforgeeks.org/replacing-strings-with-numbers-in-python-for-data-analysis/
# import pandas as pd
# import numpy as np
# dataset = pd.read_csv("/Users/kumarsanjeev/desktop/Sentiment.txt",delimiter = '\t',header=None ,names=['Review','Liked'])
# print(dataset.head())

In [25]:
# colours = {1:"positive",0:"negative"}
# colours

In [26]:
# dataset.Liked = [colours[item]for item in dataset.Liked]
# print(dataset)

# Label Encoding

In [ ]:
#https://www.geeksforgeeks.org/ml-label-encoding-of-datasets-in-python/

In [1]:
import numpy as np 
import pandas as pd 
  
# Import dataset 
df = pd.read_csv('../../data/Iris.csv') 
  
df['species'].unique() 

#Output : array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

FileNotFoundError: File b'../../data/Iris.csv' does not exist

In [ ]:
 #Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['species']= label_encoder.fit_transform(df['species']) 
  
df['species'].unique() 
#Output:array([0, 1, 2], dtype=int64)

# Sentiment Analysis code

In [2]:
#https://www.geeksforgeeks.org/python-nlp-analysis-of-restaurant-reviews/
import pandas as pd
import numpy as np
dataset = pd.read_csv("/Users/kumarsanjeev/desktop/Sentiment.txt",delimiter = '\t',header=None ,names=['Review','Liked'])
print(dataset.head())

# library to clean data 
import re  
  
# Natural Language Tool Kit 
import nltk  
  
nltk.download('stopwords') 
  
# to remove stopword 
from nltk.corpus import stopwords 
  
# for Stemming propose  
from nltk.stem.porter import PorterStemmer 
from nltk.stem import WordNetLemmatizer
# Initialize empty array 
# to append clean text  
corpus = []  
  
# 1000 (reviews) rows to clean 
for i in range(0, 1000):  
      
    # column : "Review", row ith 
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])  
      
    # convert all cases to lower cases 
    review = review.lower()  
      
    # split to array(default delimiter is " ") 
    review = review.split()  
      
    # creating PorterStemmer object to 
    # take main stem of each word 
    ps = WordNetLemmatizer()  
      
    # loop for stemming each word 
    # in string array at ith row     
    review = [ps.lemmatize(word) for word in review 
                if not word in set(stopwords.words('english'))]  
                  
    # rejoin all string array elements 
    # to create back into a string 
    review = ' '.join(review)   
      
    # append each string to create 
    # array of clean text  
    corpus.append(review)  
corpus    



FileNotFoundError: File b'/Users/kumarsanjeev/desktop/Sentiment.txt' does not exist

In [5]:
# Creating the Bag of Words model 
from sklearn.feature_extraction.text import TfidfVectorizer
  
# To extract max 1500 feature. "max_features" is attribute to experiment with to get better results 
vectorizer = TfidfVectorizer(max_features = 1500)  

# X contains corpus (dependent variable) 
X = vectorizer.fit_transform(corpus).toarray()  
words = vectorizer.get_feature_names()  
#print(words)
# y contains answers if review  is positive or negative 
y = dataset.iloc[:, 1].values 
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [20]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [21]:
from sklearn.ensemble import RandomForestClassifier 
  
# n_estimators can be said as number of 
# trees, experiment with n_estimators 
# to get better results  
model = RandomForestClassifier(n_estimators = 501, 
                            criterion = 'entropy') 
                              
model.fit(X_train, y_train)  

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=501, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [22]:
y_pred = model.predict(X_test) 
  
y_pred 

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0])

In [23]:
# Making the Confusion Matrix 
from sklearn.metrics import confusion_matrix 
  
cm = confusion_matrix(y_test, y_pred) 
  
cm 

array([[111,  14],
       [ 48,  77]])

In [24]:
validation_text = [ "I hate this place"]
a = vectorizer.transform(validation_text)
b= model.predict(a)
b

array([1])

# replacing Labels(strings)with numbers

In [75]:
#https://www.geeksforgeeks.org/replacing-strings-with-numbers-in-python-for-data-analysis/
import pandas as pd
data = pd.read_csv("/Users/kumarsanjeev/Desktop/Cars.csv")
data

Company  Price  Make  Colour
0       Honda   5000  2004     Red
1        Merc  15000  2010    Blue
2      Jaguar  23000  2015  Orange
3  Volkswagon   8000  2018   White

In [76]:
colours = {"Red":1,"Blue":2,"Orange":3,"White":4}
colours

{'Red': 1, 'Blue': 2, 'Orange': 3, 'White': 4}

In [77]:
data.Colour = [colours[item]for item in data.Colour]
print(data)



      Company  Price  Make  Colour
0       Honda   5000  2004       1
1        Merc  15000  2010       2
2      Jaguar  23000  2015       3
3  Volkswagon   8000  2018       4
